name: Package CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  validate:
    name: Validate changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: ["beta", "stable"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
